### ISSUE TITLE
bash: captainhook: command not found

### ISSUE THREAD

**Issue by Jfach** [bketelsen/captainhook#20]
Title says all. I assume it should be available after running `go get github.com/bketelsen/captainhook`, however this does not seem to be the case.

**Comment by Jfach** [comment]
Initially forgot to build captainhook, but I'm still getting the same problem after `go build .` and then trying.

**Comment by Jfach** [comment]
@sometheycallme

**Comment by sometheycallme** [comment]
Yea, we're all set with this https://github.com/cleanerbot/ansible-security/issues/30

@Jfach you can close this issue.

**Comment by sometheycallme** [comment]
```go get``` does the build of the binary and we moved it to /usr/bin during out tests.
