### ISSUE TITLE
Make post data available

### ISSUE THREAD

**Issue by analytically** [bketelsen/captainhook#8]
Write it to /tmp and use {{ postBodyFileName }} in the script? One can then eg use http://stedolan.github.io/jq/ to read it in?

**Comment by kelcecil** [comment]
I'm interested in something similar to this as well. My specific case is that I'm using captainhook to listen for a call from Docker Hub to let me know an automated build is finished to update the container. Docker Hub includes a callback URL that I need to call to indicate a successful deploy (wish I could disable this, but I can't.)

How about adding an option to dump http calls including the body data to a log file? That works for my purposes as I can tail the log, verify the where the callback came from, and get what I need from another script. If that wouldn't work, then what do you have in mind to make it "secure"? Something like requiring a token for calls? I'm willing to supply said PR if I can get a good idea of what would be acceptable.

**Comment by bketelsen** [comment]
Why not pass the body of the POST message as an argument to the shell 
script?

then the shell script could use ${@} or ${1} to see the data passed in.

Then it's up to you to ensure that the data you parse in the shell 
script won't cause your computer/application harm.

I'd take a PR like that.  If you have other ideas, I'm open.

**Comment by jaredly** [comment]
I'd suggest instead passing the body as stdin. That way if the post body is JSON (rather likely), you can parse it yourself.

**Comment by bketelsen** [comment]
closed with #11
